name: ðŸš€ Deploy Dist Folder to Hosting

on:
  push:
    branches:
      - main # setiap kali kamu push ke branch main, auto upload ke hosting

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.itsmcdani.com
          username: ${{ secrets.USER }}
          password: ${{ secrets.PW }}
          local-dir: ./
          server-dir: /public_html/
