name: ðŸš€ Deploy to Hosting

on:
  push:
    branches:
      - main # branch utama kamu

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build Its McDani
        run: |
          npm install
          npm run build

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.itsmcdani.com
          username: ${{ secrets.USER }}
          password: ${{ secrets.PW }}
          local-dir: dist
          server-dir: /public_html/
